export const STORAGE_KEY = 'msa_compliance_tracker_v1';

export const FILTER_OPTIONS = {
  categories: [
    'all',
    'Governance',
    'Financial',
    'Legislative',
    'Membership',
    'Land',
    'MSGC',
    'Ministerial',
    'Tribunal',
    'Transparency',
    'Oversight',
  ],
  types: [
    'all',
    'Meeting',
    'Election',
    'Procedural',
    'Documentation',
    'Financial',
    'Planning',
    'Reporting',
    'Legislative',
    'Notice',
    'Review',
    'Compliance',
    'Adjudication',
    'Administrative',
    'Legal',
  ],
  parties: [
    'all',
    'Settlement Council',
    'Settlement Administrator',
    'General Council',
    'Appeal Tribunal',
    'Settlement Chair',
    'Applicant/Settlement Member',
    'Occupier',
    'Obligated Operator',
    'Minister of Indigenous Relations',
    'MSAT',
    'MSLR Registrar',
    'Ethics Commissioner',
    'FOIP Coordinator',
    'Public Agency Secretariat',
  ],
  priorities: ['all', 'Critical', 'High', 'Medium', 'Low'],
};

export const CHART_COLORS = [
  '#ef4444',
  '#f59e0b',
  '#10b981',
  '#3b82f6',
  '#6366f1',
  '#f43f5e',
  '#06b6d4',
  '#84cc16',
  '#22c55e',
  '#eab308',
  '#8b5cf6',
  '#a855f7',
];
